name: Test and Deploy

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test action
        id: test-step
        uses: ./
        with:
          gradle-wrapper-path: "./test/gradle-wrapper.properties"

      - name: Check the Java version
        run: "[[ ${{ steps.test-step.outputs.java-version }} = 17 ]]"
        shell: bash

  release:
    needs: [test]
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npx semantic-release